version: '3.8'

services:
  # 1. O Site (Streamlit)
  web:
    build: .
    container_name: diskleads_web
    restart: always
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./data:/app/data  # Compartilha a pasta de dados
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0

  # 2. O Atualizador de Dados (Updater)
  updater:
    build: .
    container_name: diskleads_updater
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data  # Compartilha a MESMA pasta
    command: python updater.py

  # 3. O Robô de E-mail (Disparo) - NOVO!
  disparo:
    build: .
    container_name: diskleads_email
    restart: always
    env_file:
      - .env
    command: python disparo.py